
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: candidates
      description: "candidate combined table"
      columns:
          - name: id , client_name
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
sources:
  - name: information_sch
    database: FIVETRAN_DATABASE
    schema: INFORMATION_SCHEMA
    tables:
      - name: tables
